[project]
name = ""
version = "0.0.1"
dependencies = [
    "ansible==11.7.0",
    "ansible-lint==25.6.1",
    "ansible-creator==25.6.0",
    "boto3== 1.38.40",
    "mitogen==0.3.24",
    "yamllint==1.37.1",
    "molecule==25.6.0",
    "molecule-plugins[ec2]==23.6.0",
    "molecule-plugins[docker]==23.6.0",
    "molecule-plugins[vagrant]==23.6.0",
]

[dependency-groups]
dev = []

[tool.uv]
package = false

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
