[project]
name = ""
version = "0.0.1"
dependencies = [

  # Dependencies with set versions - pinned for stability and compatibility:

  "ansible         == 11.8.0",
  "ansible-lint    == 25.7.0",
  "ansible-creator == 25.7.1",
  "mitogen         == 0.3.26",
  "pre-commit      ==  4.2.0",
  "yamllint        == 1.37.1",

  # Dependencies set to use the latest version - to allow easy access to new features:

  "boto3",

  # Dependencies pinned to older versions due to compatibility issues with other packages:

  "molecule                  == 24.12.0",
  "molecule-plugins[ec2]     ==  23.6.0",
  "molecule-plugins[docker]  ==  23.6.0",
  "molecule-plugins[vagrant] ==  23.6.0",
]

[dependency-groups]
dev = []

[tool.uv]
package = false

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
