[project]
name = ""
version = "0.0.1"
dependencies = [
  "ansible          ==  11.8.0",
  "ansible-lint     ==  25.6.1",
  "ansible-creator  ==  25.7.0",
  "boto3            == 1.39.14",
  "mitogen          ==  0.3.24",
  "pre-commit       ==   4.2.0",
  "yamllint         ==  1.37.1",

  # Dependencies kept back due to compatibility issues:

  "molecule                   == 24.12.0",
  "molecule-plugins[ec2]      ==  23.6.0",
  "molecule-plugins[docker]   ==  23.6.0",
  "molecule-plugins[vagrant]  ==  23.6.0",
]

[dependency-groups]
dev = []

[tool.uv]
package = false

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
